name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: lint
      uses: Roang-zero1/factorio-mod-luacheck@v1.1.0
      with:
          luacheckrc_url: https://raw.githubusercontent.com/veger/Factorio-luacheckrc/ignore-tests/.luacheckrc
